<a href="https://colab.research.google.com/github/ucfilho/Metodos_Numericos_2021/blob/main/Mod_04_class_01_EDP_List_comprehension_and_put_values_inside_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
A = np.zeros((5,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
lista1 = [1,2,3,4,5]

In [22]:
lista2 =[i+1 for i in range(5)]

In [23]:
print(lista2)
print(lista1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [24]:
A[0,:] = [i+1 for i in range(5)]
print(A)

[[1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
B = np.zeros((10,10))
for i in range(10):
  calculo =(i+1) % 2
  multiplo3 =(i+1) % 3
  if(calculo == 0) and (multiplo3 != 0):
    B[i,i] = 2
  elif(multiplo3 == 0):
    B[i,i] = 7
  else:
    B[i,i] = 1
print(B)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]]


In [ ]:
C = np.zeros((12,12))
C[0,:] =[i+1 if i<5 else -3 for i in range(12)]
print(C)