<a href="https://colab.research.google.com/github/ucfilho/Metodos_Numericos_2021/blob/main/Programacao_Basica_01_mar_23_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
mM=30
xm =0.7
valor_M = mM* xm
print('valor_M separado',valor_M)

valor_M separado 21.0


In [3]:
Quantidades = [30, 25, 10]
Recupera = [0.70, 0.80, 0.90]
Num = 3
for i in range(Num):
  valor_separado = Quantidades[i]*Recupera[i]
  print('valor reparado',valor_separado)

valor reparado 21.0
valor reparado 20.0
valor reparado 9.0


In [4]:
Quantidades = [30, 25, 10]
Recupera = [0.70, 0.80, 0.90]
Resposta = []
Num = len(Quantidades)
for i in range(Num):
  valor_separado = Quantidades[i]*Recupera[i]
  Resposta.append(valor_separado)
print(Resposta)

[21.0, 20.0, 9.0]


In [5]:
Quantidades = [30, 25, 10]
Recupera = [0.70, 0.80, 0.90]
Nomes =['M','E','P']
Resposta = []
Num = len(Quantidades)
for i in range(Num):
  valor_separado = Quantidades[i]*Recupera[i]
  Resposta.append(valor_separado)

for k in range(Num):
  print('componente',Nomes[k], Resposta[k])

componente M 21.0
componente E 20.0
componente P 9.0


In [6]:

df = pd.DataFrame({'Nome': Nomes,'Quant':Quantidades,'Recupera %':Recupera,'Recuperado':Resposta})
print(df)

  Nome  Quant  Recupera %  Recuperado
0    M     30         0.7        21.0
1    E     25         0.8        20.0
2    P     10         0.9         9.0


In [7]:

Quant =np.array([30, 25, 10]) 
Recup = np.array([0.70, 0.80, 0.90])
Resp = Quant*Recup
print(Resp)

[21. 20.  9.]


In [8]:
A = np.array([[0.9,0.3,0.1],[0.1,0.5,0.2],[0.0,0.2,0.7]])
b = np.array([30.0,25.0,10.0])
print(A)

[[0.9 0.3 0.1]
 [0.1 0.5 0.2]
 [0.  0.2 0.7]]


In [9]:
print(b)

[30. 25. 10.]


In [10]:
print(A[0,1])

0.3


In [11]:
print(A[0,:])

[0.9 0.3 0.1]


In [12]:
print(A[:,0])

[0.9 0.1 0. ]


In [13]:
print(A[:,:-1])

[[0.9 0.3]
 [0.1 0.5]
 [0.  0.2]]


In [15]:
M = np.zeros((3,4))
M[:,:-1] = A
M[:,3] = b
print(M)

[[ 0.9  0.3  0.1 30. ]
 [ 0.1  0.5  0.2 25. ]
 [ 0.   0.2  0.7 10. ]]
